# Generated by Django 5.0.8 on 2024-08-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
