# Generated by Django 5.0.8 on 2024-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_pricing_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pricing_tier',
            field=models.ManyToManyField(blank=True, to='content.pricing'),
        ),
    ]
