# Generated by Django 5.0.8 on 2024-09-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_course_pricing_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pricing_tier',
        ),
        migrations.AddField(
            model_name='course',
            name='pricing_tiers',
            field=models.ManyToManyField(to='content.pricing'),
        ),
    ]
